name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  release:
    types: [published]

jobs:
  macos:
    runs-on: macOS-14
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: SPM tests
      run: swift test --enable-code-coverage
    - name: Convert coverage files
      run: |
        xcrun llvm-cov export -format "lcov" \
          .build/debug/jmespath.swiftPackageTests.xctest/Contents/MacOs/jmespath.swiftPackageTests \
          -ignore-filename-regex="\/Tests\/" \
          -instr-profile=.build/debug/codecov/default.profdata > info.lcov
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v4
      with:
        file: info.lcov

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
          - swift:5.9
          - swift:5.10
          - swift:6.0
    container:
      image: ${{ matrix.tag }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Test
      run: swift test --enable-test-discovery --enable-code-coverage --sanitize=thread
    - name: Convert coverage files
      run: |
        llvm-cov export -format="lcov" \
          .build/debug/jmespath.swiftPackageTests.xctest \
          -ignore-filename-regex="\/Tests\/" \
          -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v4
      with:
        file: info.lcov

  windows:
    runs-on: windows-latest
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-6.0-release
          tag: 6.0-RELEASE
      - uses: actions/checkout@v4
      - run: swift test