name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  release:
    types: [published]

jobs:
  macos:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: SPM tests
      run: swift test --enable-code-coverage --sanitize=thread
    - name: Convert coverage files
      run: |
        xcrun llvm-cov export -format "lcov" \
          .build/debug/jmespath.swiftPackageTests.xctest/Contents/MacOs/jmespath.swiftPackageTests \
          -ignore-filename-regex="\/Tests\/" \
          -instr-profile=.build/debug/codecov/default.profdata > info.lcov
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
      with:
        file: info.lcov

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
          - swift:5.1
          - swift:5.3
          - swift:5.4
    container:
      image: ${{ matrix.tag }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Test
      run: swift test --enable-test-discovery --enable-code-coverage --sanitize=thread
    - name: Convert coverage files
      run: |
        llvm-cov export -format="lcov" \
          .build/debug/jmespath.swiftPackageTests.xctest \
          -ignore-filename-regex="\/Tests\/" \
          -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
      with:
        file: info.lcov
